<a href="https://colab.research.google.com/github/muskanmathur2706-cloud/dataCleaningpd/blob/main/SalaryData.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
'''from google.colab import files
uploades= files.upload()'''

'from google.colab import files\nuploades= files.upload()'

In [5]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [6]:
df=pd.read_csv('Salary_Data.csv')

In [7]:
df.head()

,Age,Gender,Education Level,Job Title,Years of Experience,Salary
0,32,Male,Bachelor's,Software Engineer,5.0,90000.0
1,28,Female,Master's,Data Analyst,3.0,65000.0
2,45,Male,PhD,Senior Manager,15.0,150000.0
3,36,Female,Bachelor's,Sales Associate,7.0,60000.0
4,52,Male,Master's,Director,20.0,200000.0

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6702 entries, 0 to 6701
Data columns (total 6 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Age                  6702 non-null   int64
 1   Gender               6702 non-null   object
 2   Education Level      6701 non-null   object
 3   Job Title            6702 non-null   object
 4   Years of Experience  6701 non-null   float64
 5   Salary               6699 non-null   float64
dtypes: float64(2), int64(1), object(3)
memory usage: 314.3+ KB

In [9]:
df.describe()

               Age  Years of Experience         Salary
count  6702.000000          6701.000000    6699.000000
mean     33.620859             8.094687  115326.964771
std       7.614633             6.059003   52786.183911
min      21.000000             0.000000     350.000000
25%      28.000000             3.000000   70000.000000
50%      32.000000             7.000000  115000.000000
75%      38.000000            12.000000  160000.000000
max      62.000000            34.000000  250000.000000

In [10]:
df['Education Level'].unique()

array(["Bachelor's", "Master's", 'PhD', "Bachelor's Degree",
       "Master's Degree", nan, 'High School', 'phD'], dtype=object)

In [11]:
df['Education Level']=df['Education Level'].replace("Bachelor's","Bachelor's Degree")

In [12]:
df['Education Level']=df['Education Level'].replace("Master's","Master's Degree")

In [13]:
df['Education Level']=df['Education Level'].replace("phD","PhD")

In [14]:
df['Education Level'].unique()

array(["Bachelor's Degree", "Master's Degree", 'PhD', nan, 'High School'],
      dtype=object)

In [15]:
df.head()

,Age,Gender,Education Level,Job Title,Years of Experience,Salary
0,32,Male,Bachelor's Degree,Software Engineer,5.0,90000.0
1,28,Female,Master's Degree,Data Analyst,3.0,65000.0
2,45,Male,PhD,Senior Manager,15.0,150000.0
3,36,Female,Bachelor's Degree,Sales Associate,7.0,60000.0
4,52,Male,Master's Degree,Director,20.0,200000.0

In [16]:
df['Years of Experience'].skew()

np.float64(0.981187602540142)

In [17]:
df['Years of Experience']=df['Years of Experience'].fillna(df['Years of Experience'].mean())

In [18]:
df['Education Level']=df['Education Level'].fillna(df['Education Level'].mode()[0])

In [19]:
df['Salary'].skew()

np.float64(0.05734392354615517)

In [20]:
df['Salary']=df['Salary'].fillna(df['Salary'].mean())

In [21]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6702 entries, 0 to 6701
Data columns (total 6 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Age                  6702 non-null   int64
 1   Gender               6702 non-null   object
 2   Education Level      6702 non-null   object
 3   Job Title            6702 non-null   object
 4   Years of Experience  6702 non-null   float64
 5   Salary               6702 non-null   float64
dtypes: float64(2), int64(1), object(3)
memory usage: 314.3+ KB

In [22]:
df=pd.get_dummies(df,columns=['Gender'],drop_first=True)

In [23]:
df.head()

,Age,Education Level,Job Title,Years of Experience,Salary,Gender_Male,Gender_Other
0,32,Bachelor's Degree,Software Engineer,5.0,90000.0,True,False
1,28,Master's Degree,Data Analyst,3.0,65000.0,False,False
2,45,PhD,Senior Manager,15.0,150000.0,True,False
3,36,Bachelor's Degree,Sales Associate,7.0,60000.0,False,False
4,52,Master's Degree,Director,20.0,200000.0,True,False

Ordinal Encoding

In [24]:
from sklearn.preprocessing import OrdinalEncoder

In [25]:
oe=OrdinalEncoder(categories=[["High School","Bachelor's Degree","Master's Degree","PhD"]])

In [26]:
df['Education Level']=oe.fit_transform(df[['Education Level']])

In [27]:
df.head()

,Age,Education Level,Job Title,Years of Experience,Salary,Gender_Male,Gender_Other
0,32,1.0,Software Engineer,5.0,90000.0,True,False
1,28,2.0,Data Analyst,3.0,65000.0,False,False
2,45,3.0,Senior Manager,15.0,150000.0,True,False
3,36,1.0,Sales Associate,7.0,60000.0,False,False
4,52,2.0,Director,20.0,200000.0,True,False

In [28]:
print(df['Job Title'].unique())

['Software Engineer' 'Data Analyst' 'Senior Manager' 'Sales Associate'
 'Director' 'Marketing Analyst' 'Product Manager' 'Sales Manager'
 'Marketing Coordinator' 'Senior Scientist' 'Software Developer'
 'HR Manager' 'Financial Analyst' 'Project Manager' 'Customer Service Rep'
 'Operations Manager' 'Marketing Manager' 'Senior Engineer'
 'Data Entry Clerk' 'Sales Director' 'Business Analyst' 'VP of Operations'
 'IT Support' 'Recruiter' 'Financial Manager' 'Social Media Specialist'
 'Software Manager' 'Junior Developer' 'Senior Consultant'
 'Product Designer' 'CEO' 'Accountant' 'Data Scientist'
 'Marketing Specialist' 'Technical Writer' 'HR Generalist'
 'Project Engineer' 'Customer Success Rep' 'Sales Executive' 'UX Designer'
 'Operations Director' 'Network Engineer' 'Administrative Assistant'
 'Strategy Consultant' 'Copywriter' 'Account Manager'
 'Director of Marketing' 'Help Desk Analyst' 'Customer Service Manager'
 'Business Intelligence Analyst' 'Event Coordinator' 'VP of Finance'
 'Graphic Designer' 'UX Researcher' 'Social Media Manager'
 'Director of Operations' 'Senior Data Scientist' 'Junior Accountant'
 'Digital Marketing Manager' 'IT Manager'
 'Customer Service Representative' 'Business Development Manager'
 'Senior Financial Analyst' 'Web Developer' 'Research Director'
 'Technical Support Specialist' 'Creative Director'
 'Senior Software Engineer' 'Human Resources Director'
 'Content Marketing Manager' 'Technical Recruiter' 'Sales Representative'
 'Chief Technology Officer' 'Junior Designer' 'Financial Advisor'
 'Junior Account Manager' 'Senior Project Manager' 'Principal Scientist'
 'Supply Chain Manager' 'Senior Marketing Manager' 'Training Specialist'
 'Research Scientist' 'Junior Software Developer'
 'Public Relations Manager' 'Operations Analyst'
 'Product Marketing Manager' 'Senior HR Manager' 'Junior Web Developer'
 'Senior Project Coordinator' 'Chief Data Officer'
 'Digital Content Producer' 'IT Support Specialist'
 'Senior Marketing Analyst' 'Customer Success Manager'
 'Senior Graphic Designer' 'Software Project Manager'
 'Supply Chain Analyst' 'Senior Business Analyst'
 'Junior Marketing Analyst' 'Office Manager' 'Principal Engineer'
 'Junior HR Generalist' 'Senior Product Manager'
 'Junior Operations Analyst' 'Senior HR Generalist'
 'Sales Operations Manager' 'Senior Software Developer'
 'Junior Web Designer' 'Senior Training Specialist'
 'Senior Research Scientist' 'Junior Sales Representative'
 'Junior Marketing Manager' 'Junior Data Analyst'
 'Senior Product Marketing Manager' 'Junior Business Analyst'
 'Senior Sales Manager' 'Junior Marketing Specialist'
 'Junior Project Manager' 'Senior Accountant' 'Director of Sales'
 'Junior Recruiter' 'Senior Business Development Manager'
 'Senior Product Designer' 'Junior Customer Support Specialist'
 'Senior IT Support Specialist' 'Junior Financial Analyst'
 'Senior Operations Manager' 'Director of Human Resources'
 'Junior Software Engineer' 'Senior Sales Representative'
 'Director of Product Management' 'Junior Copywriter'
 'Senior Marketing Coordinator' 'Senior Human Resources Manager'
 'Junior Business Development Associate' 'Senior Account Manager'
 'Senior Researcher' 'Junior HR Coordinator' 'Director of Finance'
 'Junior Marketing Coordinator' 'Junior Data Scientist'
 'Senior Operations Analyst' 'Senior Human Resources Coordinator'
 'Senior UX Designer' 'Junior Product Manager'
 'Senior Marketing Specialist' 'Senior IT Project Manager'
 'Senior Quality Assurance Analyst' 'Director of Sales and Marketing'
 'Senior Account Executive' 'Director of Business Development'
 'Junior Social Media Manager' 'Senior Human Resources Specialist'
 'Senior Data Analyst' 'Director of Human Capital'
 'Junior Advertising Coordinator' 'Junior UX Designer'
 'Senior Marketing Director' 'Senior IT Consultant'
 'Senior Financial Advisor' 'Junior Business Operations Analyst'
 'Junior Social Media Specialist' 'Senior Product Development Manager'
 'Junior Operations Manager' 'Senior Software Architect'
 'Junior Research Scientist' 'Senior Financial Manager'
 'Senior HR Specialist' 'Senior Data Engineer'
 'Junior Operations Coordinator' 'Director of HR'
 'Senior Operations Coordinator' 'Junior Financial Advisor'
 'Director of Engineering' 'Software Engineer Manager'
 'Back end Developer' 'Senior Project Engineer' 'Full Stack Engineer'
 'Front end Developer' 'Developer' 'Front End Developer'
 'Director of Data Science' 'Human Resources Coordinator'
 'Junior Sales Associate' 'Human Resources Manager'
 'Juniour HR Generalist' 'Juniour HR Coordinator'
 'Digital Marketing Specialist' 'Receptionist' 'Marketing Director'
 'Social M' 'Social Media Man' 'Delivery Driver']

Features and Target

In [29]:
X=df[['Age','Education Level','Years of Experience']]

In [30]:
X.head()

   Age  Education Level  Years of Experience
0   32              1.0                  5.0
1   28              2.0                  3.0
2   45              3.0                 15.0
3   36              1.0                  7.0
4   52              2.0                 20.0

In [31]:
y=df['Salary']

In [32]:
from sklearn.model_selection import train_test_split

In [33]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

Feature Scaling

In [34]:
from sklearn.preprocessing import MinMaxScaler

In [35]:
scaler=MinMaxScaler()

In [36]:
X_train[["Age","Years of Experience"]]=scaler.fit_transform(X_train[["Age","Years of Experience"]])
X_test[["Age","Years of Experience"]]=scaler.transform(X_test[["Age","Years of Experience"]])

In [37]:
X_train.head()

           Age  Education Level  Years of Experience
4939  0.121951              1.0             0.147059
135   0.439024              1.0             0.294118
2251  0.024390              1.0             0.029412
3428  0.268293              1.0             0.058824
5356  0.146341              1.0             0.058824

Model Training

In [38]:
from sklearn.linear_model import LinearRegression

In [39]:
model=LinearRegression()

In [40]:
model.fit(X_train, y_train)

LinearRegression()

In [41]:
y_prediction=model.predict(X_test)

In [42]:
print(y_prediction)

[119603.14070126 177613.8023635   77922.28858654 ... 161277.34171754
 167408.77991271  67715.04910294]

In [43]:
print(y_test)

5071    120000.0
4462    157000.0
5557     80000.0
6540     40000.0
263      40000.0
          ...
2155    185000.0
2298    180000.0
3505    140000.0
5632    170000.0
2984     55935.0
Name: Salary, Length: 1341, dtype: float64

Evaluation Matrices

1.Mean Absolute Error
2.Mean Squared Error
3.R2 Score

In [44]:
from sklearn.metrics import mean_absolute_error,mean_squared_error,r2_score

In [45]:
mea = mean_absolute_error(y_prediction,y_test)
print(mea)

22145.305585243244

In [46]:
mea = mean_squared_error(y_prediction,y_test)
print(mea)

810907388.476432

In [47]:
r2 = r2_score(y_prediction,y_test)
print(r2)

0.5908484284253008

In [48]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6702 entries, 0 to 6701
Data columns (total 7 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Age                  6702 non-null   int64
 1   Education Level      6702 non-null   float64
 2   Job Title            6702 non-null   object
 3   Years of Experience  6702 non-null   float64
 4   Salary               6702 non-null   float64
 5   Gender_Male          6702 non-null   bool
 6   Gender_Other         6702 non-null   bool
dtypes: bool(2), float64(3), int64(1), object(1)
memory usage: 275.0+ KB

User Input

In [49]:
def user_input():
  age=int(input("Enter Age:"))
  exp=float(input("Enter Years of Experience:"))
  edu=float(input("Enter Education Level(0 for High School,1 for Bachelor's Degree,2 for Master's Degree,3 for PhD"))

  #Create a Dataframe
  user_data = pd.DataFrame([[age,edu,exp]],columns=["Age","Education Level","Years of Experience"])
  prediction = model.predict(user_data)
  print("Predicted Salary:",user_prediction[0])

In [ ]:
user_input()